Repository platinumazure/eslint-plugin-qunit, pull requests merged in 2021-03, with the labels that each got.

#151 Require eslint 6+ as peer dependency
  .github/workflows/ci.yml
  package.json
Labels: accepted, breaking, build

#152 Drop Node 13 support
  .github/workflows/ci.yml
  package.json
Labels: accepted, breaking, build

#153 Update `fixToNotOk` rule option default to true in `no-negated-ok` rule
  docs/rules/no-negated-ok.md
  lib/rules/no-negated-ok.js
  tests/lib/rules/no-negated-ok.js
Labels: accepted, breaking, enhancement

#154 Update `fixToNotOk` rule option default to true in `no-compare-relation-boolean` rule
  docs/rules/no-compare-relation-boolean.md
  lib/rules/no-compare-relation-boolean.js
  tests/lib/rules/no-compare-relation-boolean.js
Labels: accepted, breaking, enhancement

#158 Update `require-expect` rule to default to `expect-simple` option
  docs/rules/require-expect.md
  index.js
  lib/rules/require-expect.js
  tests/lib/rules/require-expect.js
Labels: accepted, breaking, enhancement

#155 Merge `two` config into `recommended` config
  README.md
  docs/rules/no-async-test.md
  docs/rules/no-global-assertions.md
  docs/rules/no-global-expect.md
  docs/rules/no-global-module-test.md
  docs/rules/no-global-stop-start.md
  docs/rules/no-init.md
  docs/rules/no-jsdump.md
  docs/rules/no-qunit-push.md
  docs/rules/no-qunit-start-in-tests.md
  docs/rules/no-qunit-stop.md
  docs/rules/no-reassign-log-callbacks.md
  docs/rules/no-reset.md
  docs/rules/no-setup-teardown.md
  docs/rules/no-test-expect-argument.md
  docs/rules/no-throws-string.md
  index.js
  scripts/update-rules.js
  tests/index.js
Labels: accepted, breaking, enhancement

#157 Add more `recommended` rules for v6
  README.md
  docs/rules/no-arrow-tests.md
  docs/rules/no-assert-equal-boolean.md
  docs/rules/no-async-module-callbacks.md
  docs/rules/no-compare-relation-boolean.md
  docs/rules/no-hooks-from-ancestor-modules.md
  docs/rules/no-nested-tests.md
  docs/rules/require-object-in-propequal.md
  index.js
Labels: accepted, breaking, enhancement

#159 Chore: Uncomment ES2020 tests in require-object-in-propequal
  tests/lib/rules/require-object-in-propequal.js
Labels: accepted, blocked, chore
