Repository platinumazure/eslint-plugin-qunit, pull requests merged in 2023-06, with the labels that each got.

#373 Drop support for Node 12, 14, 17, 19
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: breaking

#374 Strictly define Node API
  package.json
Labels: breaking

#375 Change `require-expect` rule default option to `never-except-zero`
  docs/rules/require-expect.md
  lib/rules/require-expect.js
  tests/lib/rules/require-expect.js
Labels: breaking

#376 feat!: Require eslint@^8.38, drop support for eslint@7.x
  .github/workflows/ci.yml
  package.json
Labels: breaking

#377 Upgrade dependencies in preparation for major release
  .eslintrc.json
  package-lock.json
  package.json
Labels: dependencies

#378 Use node protocol for imports
  .eslintrc.json
  lib/rules/assert-args.js
  lib/rules/literal-compare-order.js
  lib/rules/no-assert-equal-boolean.js
  lib/rules/no-assert-equal.js
  lib/rules/no-async-in-loops.js
  lib/rules/no-compare-relation-boolean.js
  lib/rules/no-negated-ok.js
  lib/rules/no-throws-string.js
  lib/rules/require-object-in-propequal.js
  lib/utils.js
  tests/index.js
Labels: chore

#379 Use `ecmaVersion` of `latest` for eslint
  .eslintrc.json
Labels: chore

#380 Tweak release-it
  package.json
Labels: chore

#383 Fix default in doc for `require-expect` rule
  docs/rules/require-expect.md
Labels: docs

#299 Test: add eslint-remote-tester
  .gitignore
  eslint-remote-tester.config.js
  package-lock.json
  package.json
Labels: chore
